apiVersion: v1
kind: Pod
metadata:
  name: test-vpa-pod
  namespace: default
  labels:
    app: test-vpa-app
spec:
  containers:
  - name: test-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    # VPA가 업데이트한 리소스 패턴
    env:
    - name: VPA_UPDATED
      value: "true"
  restartPolicy: Always
